### ISSUE TITLE
./clsrv: symbol lookup error: ./clsrv: undefined symbol: free_mem_coffer

### ISSUE THREAD

**Issue by temoto** [boggle/gozero#2]
zeromq version: tags/v2.0.6^0=ae35a1 (installed locally in my home, so i had to add -I$(HOME)/include and -L$(HOME)/include to Makefile-s below)
gonewrong version: 754648
coffer version: 19c834
gozero version: 7b78b4

$ ./clsrv
./clsrv: symbol lookup error: ./clsrv: undefined symbol: free_mem_coffer

$ ldd -r clsrv 
    linux-vdso.so.1 =>  (0x00007fffcc7ff000)
    cgo_zmq.so => /home/temoto/src/go/pkg/linux_amd64/cgo_zmq.so (0x00007f208f296000)
    libcgo.so => /home/temoto/src/go/pkg/linux_amd64/libcgo.so (0x00007f208f093000)
    cgo_unsafe_coffer.so => /home/temoto/src/go/pkg/linux_amd64/cgo_unsafe_coffer.so (0x00007f208ee90000)
    libzmq.so.0 => /home/temoto/lib/libzmq.so.0 (0x00007f208ec52000)
    libpthread.so.0 => /lib/libpthread.so.0 (0x00007f208ea11000)
    libm.so.6 => /lib/libm.so.6 (0x00007f208e78d000)
    libc.so.6 => /lib/libc.so.6 (0x00007f208e40b000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f208f49b000)
    libuuid.so.1 => /lib/libuuid.so.1 (0x00007f208e206000)
    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f208def1000)
    libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007f208dcda000)
undefined symbol: free_mem_coffer   (./clsrv)

What could be the reason of this?

Looking at the code, i suppose zmq.go:410 tries to use coffer.FreeMemCoffer by it's "direct C name", so maybe it's about that coffer exports that function with different name on my Linux amd64?

**Comment by boggle** [comment]
has been fixed but not tested on Linux; pls try current HEAD

**Comment by temoto** [comment]
likely irrelevant now
